#!/usr/bin/env python
import os, sys
from workqueues import *

USAGE = """\
workqueue TYPE:ID COMMAND ARGS...

    TYPE                ID
    directory (dir)     path to the queue's directory
    beanstalk (bean)    host:port of the queue
    zeromq    (zmq)     host:port of the queue

COMMAND


    list [after=DATE] [before=DATE] [name=GLOB] [running]

TYPES

    DATE YYYY[MM[DD[HH[MM]]]]
    GLOB a glob expression

"""

def parse_args( args ):
	if len(args) < 2:
		log(USAGE)
		return None, None, None
	else:
		queue   = args[0]
		command = args[1]
		args    = []
		if len(args) > 2: args = args[2:]
		return (queue, command, args)

def get_queue( queue ):
	qtype, qid = queue.split(":", 1)
	if qtype in ("dir", "directory"):
		return DirectoryQueue(qid)
	else:
		raise Exception("Unsupported queue type: %s" % (qtype))

def run_command( queue, command, args ):
	if command == "list":
		for job_id in queue.list():
			print queue.get(job_id)

if __name__ == "__main__":
	args = sys.argv[1:]
	queue, command, args = parse_args(args)
	if queue:
		run_command(get_queue(queue), command, args)
		

# EOF - vim: syn=python
